### ISSUE TITLE
Granular API controls?

### ISSUE THREAD

**Issue by mdbraber** [transip/gotransip#10]
This is a general question related to the API - I'm not sure where general requests could go (other than support@transip.nl), so I'm posting it here.

When issuing certificates with Let's Encrypt I'm using the TransIP API to e.g. create the needed CNAME and TXT records. But the API has access to my *full* range of domains and services. E.g. I cannot limit API access to just access a particular domain or even better: just a certain type of actions with a particular domain (e.g. just updating TXT records of example.org).

Such granular control would make it much more useful because I would be able to leave my credentials at different hosts where a possible attack would only expose a very limited set of features. 

When looking at the domain actions (which is what I'm using mostly) the current implementation only allows manipulation of the full zone (basically overwriting the whole zone). Although this seems straightforward it gives most users much more control that they would need to have.

Wondering if there is a place to suggest ideas for a possible v6.0 of the API?

**Comment by RobinGeuze** [comment]
Implementing API ACL's (which I think is what you are suggesting) is not really possible in the current API implementation, however going forward we will definitely take it into account when building a new API.

If you want you can submit a feature requests at https://www.transip.eu/knowledgebase/propose-idea/ (or transip.nl if you have an account there).

I will close this issue for now since it is not really related to this implementation.
